# Generated by Django 6.0.3 on 2026-04-13 18:01

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    Category = apps.get_model('google', 'Category')
    Category.objects.create(id=1, category_name='Uncategorized')


def reverse_default_category(apps, schema_editor):
    Category = apps.get_model('google', 'Category')
    Category.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.RunPython(
            create_default_category,
            reverse_default_category,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='google.category'),
            preserve_default=False,
        ),
    ]
