# Generated by Django 6.0.3 on 2026-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=255)),
                ('std_roll', models.CharField(max_length=50)),
                ('std_image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('std_email', models.EmailField(max_length=254)),
                ('std_city', models.CharField(max_length=100)),
            ],
        ),
    ]
